# 项目相关配置
feifan:
  # 名称
  name: feifan
  # 版本
  version: 2.0.0
  # 版权年份
  copyrightYear: 2019
  #支持的移动端类型集合,多个用英文逗号,分割
  sourceArray: 10
  # 后台接口地址
  backUrl: http://192.168.0.86:8080/ffapaas
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /itsm
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# 日志配置
logging:
  level:
    com.feifan: debug
    org.springframework: warn
    org.springframework.data.elasticsearch.client.WIRE: TRACE

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  1024MB
      # 设置总上传的文件大小
      max-request-size:  1024MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #时区
    time-zone: GMT+8